using UnityEngine;
using UnityEngine.InputSystem;
using Unity.MLAgents;
using Unity.MLAgents.Sensors;
using Unity.MLAgents.Actuators;

[RequireComponent(typeof(Rigidbody))]
public class CarAgent : Agent
{
    [Header("References")]
    [Tooltip("Checkpoints generated by CheckpointRecorder. Ensures perfect road alignment.")]
    public Transform[] checkpoints;
    [Tooltip("The original start position on the track.")]
    public Transform spawnPoint;

    [Header("Driving Physics")]
    public float maxSteerAngle = 150f;
    public float speedLimit = 5f;               // Lowered from 8f to make the car drive slow and learn carefully
    public float decelerationRate = 10f;
    const float spawnGracePeriod = 0.15f;       // Clean grace period for physics to settle on spawn

    [Header("Reward & Rules")]
    public float progressRewardScale = 0.2f;    // Refactored to segment-crossing trigger logic
    public float edgePenalty = -5.0f;           // Heavy crash penalty
    public float checkpointRadius = 4f; 
    [Tooltip("Max distance the car can drift from the road segment before triggering a crash reset.")]
    public float maxAllowedDistanceFromTrack = 20f;
    public bool manualDrivingMode = false;

    Rigidbody rb;
    int nextCheckpoint = 0;
    float minDistToCheckpoint = float.MaxValue;
    float stuckTimer = 0f;
    float episodeTimer = 0f;
    float wrongWayTimer = 0f;

    // Displacement tracker for robust stuck checks (immune to contact physics jitter)
    Vector3 lastPosition;
    float lastPositionCheckTime = 0f;
    float stuckAccumulator = 0f;

    // Checkpoint-based spawn logic (N-1 rule)
    int spawnCheckpointIndex = 0;

    public override void Initialize()
    {
        rb = GetComponent<Rigidbody>();
        if (spawnPoint == null)
        {
            GameObject spObj = GameObject.Find("SpawnPoint");
            if (spObj != null) spawnPoint = spObj.transform;
            else Debug.LogWarning("SpawnPoint not found in scene!");
        }
    }

    public override void OnEpisodeBegin()
    {
        if (spawnPoint == null && (checkpoints == null || checkpoints.Length == 0)) return;

        Vector3 sp;
        Quaternion sr;

        if (spawnCheckpointIndex == 0)
        {
            sp = spawnPoint != null ? spawnPoint.position : checkpoints[0].position;
            sr = spawnPoint != null ? spawnPoint.rotation : checkpoints[0].rotation;
        }
        else
        {
            sp = checkpoints[spawnCheckpointIndex].position;
            sr = checkpoints[spawnCheckpointIndex].rotation;
        }

        // Apply road height + natural standing height from your prefab
        float naturalHeightOffset = (spawnPoint != null) ? (spawnPoint.position.y - checkpoints[0].position.y) : 0f;
        sp.y = checkpoints[spawnCheckpointIndex].position.y + naturalHeightOffset;

        transform.position = sp;
        transform.rotation = sr;

        rb.linearVelocity = Vector3.zero;
        rb.angularVelocity = Vector3.zero;
        rb.WakeUp(); // Ensure PhysX wakes up the teleported Rigidbody immediately
        stuckTimer = 0f;
        episodeTimer = 0f;
        wrongWayTimer = 0f;

        // Initialize displacement checkpoint values on spawn
        lastPosition = transform.position;
        lastPositionCheckTime = 0f;
        stuckAccumulator = 0f;

        // The target is the next checkpoint
        nextCheckpoint = (spawnCheckpointIndex + 1) % checkpoints.Length;

        if (checkpoints != null && checkpoints.Length > 0)
        {
            Vector2 flatPos = new Vector2(transform.position.x, transform.position.z);
            Vector2 flatCP = new Vector2(checkpoints[nextCheckpoint].position.x, checkpoints[nextCheckpoint].position.z);
            minDistToCheckpoint = Vector2.Distance(flatPos, flatCP);
        }
    }

    public override void CollectObservations(VectorSensor sensor)
    {
        // 1. Basic Kinematics (2 obs)
        sensor.AddObservation(rb.linearVelocity.magnitude / speedLimit);
        sensor.AddObservation(Vector3.Dot(transform.forward, rb.linearVelocity.normalized));

        // 2. ADVANCED SENSOR: Virtual IMU & Slip Detection (2 obs)
        // This gives the AI physical awareness of "drifting" (sliding sideways) and "spinning" (yaw rate)
        Vector3 localVel = transform.InverseTransformDirection(rb.linearVelocity);
        sensor.AddObservation(localVel.x / speedLimit);    // Detects sideways slip
        sensor.AddObservation(rb.angularVelocity.y / 5f); // Detects how fast the car is turning its chassis

        if (checkpoints != null && checkpoints.Length > 0)
        {
            // Observation 1: Target Checkpoint
            Vector3 dirToNext = (checkpoints[nextCheckpoint].position - transform.position).normalized;
            Vector3 localDir = transform.InverseTransformDirection(dirToNext);
            sensor.AddObservation(localDir.x);
            sensor.AddObservation(localDir.z);

            // Observation 2: Lookahead (so the AI isn't blind to upcoming curves)
            int lookaheadCP = (nextCheckpoint + 1) % checkpoints.Length;
            Vector3 dirToLookahead = (checkpoints[lookaheadCP].position - transform.position).normalized;
            Vector3 localLookahead = transform.InverseTransformDirection(dirToLookahead);
            sensor.AddObservation(localLookahead.x);
            sensor.AddObservation(localLookahead.z);
        }
        else
        {
            sensor.AddObservation(0f); sensor.AddObservation(0f);
            sensor.AddObservation(0f); sensor.AddObservation(0f);
        }

        // 3. EDGE SENSORS: 11 ray distances (11 obs)
        // This gives the AI physical sight of the track edges
        CarEdgeSensors edgeSensors = GetComponent<CarEdgeSensors>();
        if (edgeSensors != null)
        {
            float[] distances = edgeSensors.GetObservations();
            for (int i = 0; i < distances.Length; i++)
            {
                sensor.AddObservation(distances[i]);
            }
        }
        else
        {
            for (int i = 0; i < 11; i++)
            {
                sensor.AddObservation(1f); // Fallback: open road
            }
        }
    }

    public override void OnActionReceived(ActionBuffers actions)
    {
        float steer = Mathf.Clamp(actions.ContinuousActions[0], -1f, 1f);
        float throttleInput = Mathf.Clamp(actions.ContinuousActions[1], -1f, 1f);
        
        episodeTimer += Time.fixedDeltaTime;
        
        // SMALL TIME PENALTY per step — discourages loitering, stationary farming, and wall-hugging
        AddReward(-0.001f);

        // For training mode (not manual driving), remap the continuous action [-1, 1] to [0, 1] range.
        // This removes the 50% passive deadzone, allowing the agent to explore forward movement.
        if (!manualDrivingMode)
        {
            throttleInput = (throttleInput + 1f) / 2f;
        }

        // CONTINUOUS EDGE PROXIMITY PENALTY
        // Read the custom edge sensors and apply a shaped penalty if very close to walls
        CarEdgeSensors edgeSensors = GetComponent<CarEdgeSensors>();
        if (edgeSensors != null)
        {
            float[] distances = edgeSensors.GetObservations();
            float minDistance = 1f;
            for (int i = 0; i < distances.Length; i++)
            {
                if (distances[i] < minDistance) minDistance = distances[i];
            }

            // Proximity threshold: 30% of max distance (e.g., 9 meters out of 30m)
            if (minDistance < 0.3f)
            {
                float safetyFactor = minDistance / 0.3f;
                // Quadratic curve: minor warning penalty at start, steep penalty very close to wall
                float proximityPenalty = Mathf.Pow(1f - safetyFactor, 2) * 0.2f;
                AddReward(-proximityPenalty * Time.fixedDeltaTime);
            }
        }

        // MANUAL OVERRIDE (For emergency unsticking)
        if (Keyboard.current != null)
        {
            if (Keyboard.current.wKey.isPressed) throttleInput = 1f;
            if (Keyboard.current.sKey.isPressed) throttleInput = -1f;
            if (Keyboard.current.aKey.isPressed) steer = -1f;
            if (Keyboard.current.dKey.isPressed) steer = 1f;
        }

        float currentSpeed = Vector3.Dot(transform.forward, rb.linearVelocity);

        // ANTI-STUCK SYSTEM (DISPLACEMENT-BASED)
        // Checked every 1.0 second to ensure immunity to physical collision jitters/spinning wheels
        if (episodeTimer - lastPositionCheckTime > 1.0f)
        {
            float distanceMoved = Vector3.Distance(transform.position, lastPosition);
            
            // If the car traveled less than 0.8 meters in 1 second, it is functionally stuck
            if (distanceMoved < 0.8f)
            {
                stuckAccumulator += 1.0f;
            }
            else
            {
                stuckAccumulator = 0f;
            }

            lastPosition = transform.position;
            lastPositionCheckTime = episodeTimer;

            float maxStuckTime = manualDrivingMode ? 10.0f : 3.0f; // Faster reset during training (3s) to accelerate exploration
            if (stuckAccumulator >= maxStuckTime)
            {
#if UNITY_EDITOR
                Debug.LogWarning($"[STUCK RESET] Car traveled only {distanceMoved:F2}m in the check interval. Total stuck accumulated: {stuckAccumulator}s");
#endif
                HandleCrash(true); // Rolled back since isStuck=true
                return;
            }
        }

        // WRONG-WAY DETECTION & CORRECTION SYSTEM
        if (checkpoints != null && checkpoints.Length > 0)
        {
            int prevCP = (nextCheckpoint - 1 + checkpoints.Length) % checkpoints.Length;
            Vector3 trackDir = (checkpoints[nextCheckpoint].position - checkpoints[prevCP].position).normalized;

            // Compute 2D (X/Z plane) alignment to ignore vertical track slopes
            Vector2 flatForward = new Vector2(transform.forward.x, transform.forward.z).normalized;
            Vector2 flatTrackDir = new Vector2(trackDir.x, trackDir.z).normalized;
            float alignment = Vector2.Dot(flatForward, flatTrackDir);

            // Compute actual speed along the track heading direction
            Vector2 flatVelocity = new Vector2(rb.linearVelocity.x, rb.linearVelocity.z);
            float trackSpeed = Vector2.Dot(flatVelocity, flatTrackDir);

            // 1. Orientation Shaping: Reward facing forward, penalize facing backward
            // Maximum alignment = 1f (no penalty). Minimum alignment = -1f (penalty = -2.0 * 0.1 = -0.2 per fixed update)
            AddReward((alignment - 1.0f) * 0.1f * Time.fixedDeltaTime);

            // 2. Reverse Travel Penalty: Deduct reward for physically driving backward along track direction
            if (trackSpeed < -0.1f)
            {
                AddReward(trackSpeed * 0.5f * Time.fixedDeltaTime); // Moving backwards at 8m/s costs -4.0 reward per second
            }

            // 3. Auto-Reset: If facing backwards (alignment < 0.0f) for 3.0 seconds, trigger wrong-way crash reset
            if (alignment < 0.0f)
            {
                wrongWayTimer += Time.fixedDeltaTime;
                if (wrongWayTimer > 3.0f)
                {
#if UNITY_EDITOR
                    Debug.LogWarning($"[WRONG-WAY RESET] Car drove backward for 3 seconds. Alignment: {alignment:F2}");
#endif
                    HandleCrash(true); // Rolled back since isStuck=true
                    return;
                }
            }
            else
            {
                wrongWayTimer = 0f;
            }
        }

        // PHYSICS
        if (throttleInput < -0.1f && currentSpeed > 1f) 
        {
            Vector3 brakeTarget = Vector3.zero;
            brakeTarget.y = rb.linearVelocity.y; // DO NOT wipe gravity when braking! (Fixes slow floating hover anomaly)
            rb.linearVelocity = Vector3.Lerp(rb.linearVelocity, brakeTarget, Time.fixedDeltaTime * decelerationRate);
        }
        else 
        {
            // Apply throttle input (even 0, acting as drag/deceleration if stationary)
            // Removing the 0.05f gate and increasing Lerp factor to 10f makes the engine power highly responsive
            Vector3 target = transform.forward * throttleInput * speedLimit;
            target.y = rb.linearVelocity.y;
            rb.linearVelocity = Vector3.Lerp(rb.linearVelocity, target, Time.fixedDeltaTime * 10f);
        }

        // DYNAMIC STEERING: Less steering at high speeds to prevent erratic spinning
        float speedRatio = Mathf.Clamp01((Mathf.Abs(currentSpeed) + 2f) / (speedLimit * 0.5f)); 
        float steerCap = Mathf.Lerp(1.0f, 0.4f, Mathf.Abs(currentSpeed) / speedLimit);
        float finalSteer = steer * maxSteerAngle * steerCap * speedRatio;
        
        // FORWARD VELOCITY REWARD — small bonus for moving forward, penalty for going backward
        if (currentSpeed > 0.5f)
        {
            AddReward(currentSpeed * 0.001f); // Tiny but directional: rewards fast forward motion
        }
        else if (currentSpeed < -0.1f)
        {
            AddReward(-0.01f); // Penalize backward movement
        }
        
        float direction = currentSpeed < -0.1f ? -1f : 1f;

        // FIX: rotate via the Rigidbody instead of the Transform.
        // Writing to transform.rotation directly on a non-kinematic Rigidbody
        // bypasses the physics pipeline; PhysX then "corrects" the resulting
        // overlaps with the ground via depenetration, which pushes the car
        // upward every FixedUpdate and shows up as slow lift-off/hovering.
        // MoveRotation keeps the rotation inside the simulated motion so
        // PhysX handles contacts correctly.
        Quaternion deltaRotation = Quaternion.Euler(0f, finalSteer * direction * Time.fixedDeltaTime, 0f);
        rb.MoveRotation(rb.rotation * deltaRotation);


        // CHECKPOINT LOGIC
        if (checkpoints != null && checkpoints.Length > 0)
        {
            Vector2 flatPos = new Vector2(transform.position.x, transform.position.z);
            Vector2 flatCP = new Vector2(checkpoints[nextCheckpoint].position.x, checkpoints[nextCheckpoint].position.z);
            float dist = Vector2.Distance(flatPos, flatCP);
            
            // Track closest distance to checkpoint (no continuous reward to prevent farming across resets)
            if (dist < minDistToCheckpoint) 
            {
                minDistToCheckpoint = dist;
            }

            // Checkpoint reached: give bonus, advance target, record new spawn milestone (N-1 rule)
            if (dist < checkpointRadius)
            {
                AddReward(2.0f); // Earned only when successfully crossing a new checkpoint barrier
                spawnCheckpointIndex = nextCheckpoint; // Lock passed checkpoint as new spawn point
                nextCheckpoint = (nextCheckpoint + 1) % checkpoints.Length;
                Vector2 newCP = new Vector2(checkpoints[nextCheckpoint].position.x, checkpoints[nextCheckpoint].position.z);
                minDistToCheckpoint = Vector2.Distance(flatPos, newCP);
            }
            // NOTE: No distance-based OOB check here.
            // The car only resets when it physically hits a wall (OnCollisionEnter / OnTriggerEnter).
            // Distance checks on curved tracks cause false resets and have been removed.
        }
    }

    public void HandleCrash(bool isStuck = false)
    {
        if (manualDrivingMode) return;

        AddReward(edgePenalty);
        EndEpisode();
    }

    public override void Heuristic(in ActionBuffers actionsOut)
    {
        var continuousActions = actionsOut.ContinuousActions;
        var kb = Keyboard.current;
        float steer = 0f, throttle = 0f;
        
        if (kb != null)
        {
            if (kb.aKey.isPressed || kb.leftArrowKey.isPressed)  steer    = -1f;
            if (kb.dKey.isPressed || kb.rightArrowKey.isPressed) steer    =  1f;
            if (kb.wKey.isPressed || kb.upArrowKey.isPressed)    throttle =  1f;
            if (kb.sKey.isPressed || kb.downArrowKey.isPressed || kb.spaceKey.isPressed) throttle = -1f;
        }
        
        continuousActions[0] = steer;
        continuousActions[1] = throttle;
    }

    void OnCollisionEnter(Collision collision)
    {
        // Grace period: ignore collisions during the first 0.15s of an episode to let physics depenetration finish safely
        if (episodeTimer < 0.15f) return;

        string objTag = collision.gameObject.tag;
        string objName = collision.gameObject.name.ToLower();

        if (objTag == "TrackEdge" || objTag == "Wall" || 
            objName.Contains("wall") || objName.Contains("edge") || objName.Contains("barrier"))
        {
#if UNITY_EDITOR
            Debug.LogWarning($"[CRASH RESET] Collision with Object: {collision.gameObject.name}, Tag: {objTag}");
#endif
            AddReward(-2.0f); // Immediate extra penalty for physically hitting a wall
            HandleCrash();
        }
    }

    void OnTriggerEnter(Collider other)
    {
        // Grace period: ignore triggers during the first 0.15s of an episode to let physics depenetration finish safely
        if (episodeTimer < 0.15f) return;

        string objTag = other.gameObject.tag;
        string objName = other.gameObject.name.ToLower();

        if (objTag == "TrackEdge" || objTag == "Wall" || 
            objName.Contains("wall") || objName.Contains("edge") || objName.Contains("barrier"))
        {
#if UNITY_EDITOR
            Debug.LogWarning($"[CRASH RESET] Trigger with Object: {other.gameObject.name}, Tag: {objTag}");
#endif
            AddReward(-2.0f); // Immediate extra penalty for entering a trigger boundary
            HandleCrash();
        }
    }

    // Helper: Distance of p from segment ab
    float DistanceToSegment(Vector2 p, Vector2 a, Vector2 b)
    {
        Vector2 ab = b - a;
        Vector2 ap = p - a;
        float ab2 = Vector2.Dot(ab, ab);
        if (ab2 < 0.0001f) return Vector2.Distance(p, a);
        float t = Vector2.Dot(ap, ab) / ab2;
        t = Mathf.Clamp01(t);
        Vector2 closest = a + t * ab;
        return Vector2.Distance(p, closest);
    }
}